[build]
  command = "npm run start"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[template.environment]
  ACKEE_MONGODB = "mongodb+srv://..."
  ACKEE_USERNAME = "admin"
  ACKEE_PASSWORD = "admin"